name: Run Python Script and Format Code on Pull Request Merge

on:
  pull_request:
    types: [closed]
     #branches:
      # - 'feature-*'
       #- master

jobs:
  run_script:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      #- name: Install dependencies
      #  run: pip install -r requirements.txt
      - name: Get list of files
        id: get_files
        run: |
          echo $(git diff --name-only HEAD^ HEAD)
          echo ::set-output name=files::$(git diff --name-only HEAD^ HEAD)
      - name: Run Python script
        run: python ./scripts/script.py ${{ steps.get_files.outputs.files }}
      - name: Get list of files from the merge commit
        id: get_files_2
        run: | 
          git fetch origin ${GITHUB_REF}
          git checkout ${GITHUB_BASE_REF}
          head=$(git rev-parse ${GITHUB_HEAD_REF})
          base=$(git merge-base $head ${GITHUB_BASE_REF})
          echo $head
          echo $base
          echo $(git diff-tree --no-commit-id --name-only $head -r)
          echo ::set-output name=files::$(git diff-tree --no-commit-id --name-only $head -r)
     
      # - name: Commit changes
      #   run: |
      #     git config --global user.email "github-actions@github.com"
      #     git config --global user.name "GitHub Actions"
      #     git commit -a -m "Format code with clang-format"
      #     git push origin HEAD:${{ github.event.pull_request.head.ref }}
