name: Run Python Script and Format Code on Pull Request Merge With 3rd Party Action

on:
  pull_request:
    types: [closed]
     #branches:
      # - 'feature-*'
       #- master

jobs:
  run_script:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      #- name: Install dependencies
      #  run: pip install -r requirements.txt
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Run Python script
        run: python ./scripts/script.py ${{ steps.changed-files.outputs.all_changed_files }}     
      # - name: Commit changes
      #   run: |
      #     git config --global user.email "github-actions@github.com"
      #     git config --global user.name "GitHub Actions"
      #     git commit -a -m "Format code with clang-format"
      #     git push origin HEAD:${{ github.event.pull_request.head.ref }}
